### PR TITLE
fix: permalink domain

### PR DESCRIPTION
**Pull request by Nedum84**

### CODE REVIEW

**Review by jhony112 — COMMENTED** [review]
@Nedum84 can we compress the images, it increases the size of the plugin very considerably

**Comment by Nedum84** [comment]
They are already compressed. Their total size is 1.3MB. Should I compress them further?

**Comment by jhony112** [comment]
yes please  let's compress them and reduce the size if need be

**Comment by jhony112** [comment]
@Nedum84

**Review by jhony112 — CHANGES_REQUESTED** [review]
nACK- please Resize images

**Comment by Nedum84** [comment]
Rezise to what size exactly?
Any size recommendation?

**Comment by jhony112** [comment]
Reduce images by 50%

**Comment by Nedum84** [comment]
Done. total size is 497KB

**Review by jhony112 — APPROVED** [review]

**Pull request merged**
